data:
  assembly_report: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.13_GRCh37/GCF_000001405.13_GRCh37_assembly_report.txt 
  genome: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.13_GRCh37/GCF_000001405.13_GRCh37_genomic.fna.gz
  chipseq:
    control_ids:
      - SRR6792585
    target_ids:
      - SRR6792586
      - SRR6792587
dir:
  data_dir: data_2025
  output_dir: output_2025
